language: python
python:
  - "3.7"
cache: pip
install:
  - sudo apt-get install graphviz
  - pip install -r requirements.txt
  - "pip install pydot-ng pyparsing"
  - "pip install graphviz"

script:
  - bash scripts/install_and_run.sh